name: Trees
options:
  bundleIdPrefix: com.treetracker
  deploymentTarget:
    iOS: "17.0"
    watchOS: "11.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: true

targets:
  Trees:
    type: application
    platform: iOS
    sources:
      - path: Trees
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    info:
      path: Trees/Info.plist
      properties:
        CFBundleDisplayName: Tree Tracker
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscageLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocationWhenInUseUsageDescription: Tree Tracker needs your location to record precise GPS coordinates of trees you capture.
        NSLocationAlwaysAndWhenInUseUsageDescription: Tree Tracker needs your location to record precise GPS coordinates of trees you capture.
        NSCameraUsageDescription: Tree Tracker uses the camera to take photos of trees for identification.
        NSPhotoLibraryUsageDescription: Tree Tracker needs access to your photos to attach existing images to tree records.
    settings:
      base:
        INFOPLIST_FILE: Trees/Info.plist
        GENERATE_INFOPLIST_FILE: false
        PRODUCT_BUNDLE_IDENTIFIER: com.treetracker.Trees
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 3L3ASPMXH9
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - target: TreesWatch
        embed: true

  TreesWatch:
    type: application
    platform: watchOS
    sources:
      - path: TreesWatch
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    info:
      path: TreesWatch/Info.plist
      properties:
        CFBundleDisplayName: Tree Tracker
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        WKApplication: true
        WKCompanionAppBundleIdentifier: com.treetracker.Trees
        WKRunsIndependentlyOfCompanionApp: true
        NSLocationWhenInUseUsageDescription: Tree Tracker needs your location to record GPS coordinates of trees.
    settings:
      base:
        INFOPLIST_FILE: TreesWatch/Info.plist
        GENERATE_INFOPLIST_FILE: false
        PRODUCT_BUNDLE_IDENTIFIER: com.treetracker.Trees.watchkitapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 3L3ASPMXH9
        WATCHOS_DEPLOYMENT_TARGET: "11.0"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - target: TreesWatchWidget
        embed: true

  TreesWatchWidget:
    type: app-extension
    platform: watchOS
    sources:
      - path: TreesWatchWidget
        excludes:
          - "**/.DS_Store"
    info:
      path: TreesWatchWidget/Info.plist
      properties:
        CFBundleDisplayName: Tree Tracker
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        INFOPLIST_FILE: TreesWatchWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.treetracker.Trees.watchkitapp.widget
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 3L3ASPMXH9
        WATCHOS_DEPLOYMENT_TARGET: "11.0"
        SKIP_INSTALL: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
